context:
  name: mambajs
  version: "0.20.3"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/emscripten-forge/mambajs/archive/v${{ version }}.tar.gz
  sha256: 1822d697c84a3bc003125bb92f8c1916cb58935451efa15c237befde1a97d0b5

build:
  number: 0

requirements:
  build:
    - yarn
    - nodejs
  host:
    - yarn
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - mambajs --help
      - mambajs --version

about:
  homepage: https://github.com/emscripten-forge/mambajs
  repository: https://github.com/emscripten-forge/mambajs
  summary: 'Mambajs CLI for generating lock files'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinRenou
