context:
  name: mambajs
  version: "0.21.5"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/emscripten-forge/mambajs/archive/v${{ version }}.tar.gz
  sha256: 9d8bd84fb26a8f9d33922184e3e24c20f749c26e6a3a9fa76362cef162df39e8

build:
  number: 0

requirements:
  build:
    - yarn =3
    - nodejs
  host:
    - yarn =3
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - mambajs --help
      - mambajs --version

about:
  homepage: https://github.com/emscripten-forge/mambajs
  repository: https://github.com/emscripten-forge/mambajs
  summary: 'Mambajs CLI for generating lock files'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinRenou
