context:
  name: mambajs
  version: "0.23.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/emscripten-forge/mambajs/archive/v${{ version }}.tar.gz
  sha256: b943cf85a3e04e1f44b986eaed562f860c57e731ed1fa03d9e544a80d84d033f

build:
  number: 0

requirements:
  build:
    - yarn =3
    - nodejs
  host:
    - yarn =3
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - mambajs --help
      - mambajs --version

about:
  homepage: https://github.com/emscripten-forge/mambajs
  repository: https://github.com/emscripten-forge/mambajs
  summary: 'Mambajs CLI for generating lock files'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinRenou
