context:
  name: mambajs
  version: "0.21.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/emscripten-forge/mambajs/archive/v${{ version }}.tar.gz
  sha256: 290ddd877ce500b523ea7ef889be92477e3becd1cc0c52b25764420f6a0811e9

build:
  number: 0

requirements:
  build:
    - yarn
    - nodejs
  host:
    - yarn
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - mambajs --help
      - mambajs --version

about:
  homepage: https://github.com/emscripten-forge/mambajs
  repository: https://github.com/emscripten-forge/mambajs
  summary: 'Mambajs CLI for generating lock files'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinRenou
