context:
  name: mambajs
  version: "0.20.2"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/emscripten-forge/mambajs/archive/v${{ version }}.tar.gz
  sha256: 0308891fe95833b086936af41409cec5d87471d4fbc6ece0b82e1d0c3a8f0076

build:
  number: 0

requirements:
  build:
    - yarn
    - nodejs
  host:
    - yarn
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - mambajs --help
      - mambajs --version

about:
  homepage: https://github.com/emscripten-forge/mambajs
  repository: https://github.com/emscripten-forge/mambajs
  summary: 'Mambajs CLI for generating lock files'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinRenou
